/**
 * Self-host the web fonts.
 *
 * The site loaded Sora, Manrope and JetBrains Mono from fonts.googleapis.com —
 * a third-party request on every page view that leaks visitor IPs to Google, is
 * blocked outright in some regions, and costs a DNS + TLS handshake before the
 * first paint. This fetches exactly the weights the site uses, keeps only the
 * latin subsets, stores the woff2 files under `public/fonts/`, and writes the
 * `@font-face` rules to `src/styles/fonts.css`.
 *
 * Run it only when the weight list below changes; the output is committed.
 *
 * Usage: node scripts/fetch-fonts.mjs
 */

import { mkdir, writeFile, rm } from 'node:fs/promises';
import { existsSync } from 'node:fs';

const FAMILIES = [
  { query: 'Sora:wght@400;600;700;800', family: 'Sora' },
  { query: 'Manrope:wght@400;500;600;700;800', family: 'Manrope' },
  { query: 'JetBrains+Mono:wght@500;600', family: 'JetBrains Mono' },
];

/** Latin only — the site is English-language; latin-ext covers accented names. */
const SUBSETS = new Set(['latin', 'latin-ext']);

/** A current desktop UA is what makes the CSS API return woff2 rather than ttf. */
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const OUT_DIR = 'public/fonts';
const OUT_CSS = 'src/styles/fonts.css';

const slug = (value) =>
  value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');

/** Pull each `subset` comment and its following @font-face block out of the response. */
function parseBlocks(css) {
  const blocks = [];
  const re = /\/\*\s*([a-z0-9-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g;
  let match;
  while ((match = re.exec(css))) blocks.push({ subset: match[1], body: match[2] });
  return blocks;
}

const field = (body, name) => body.match(new RegExp(`${name}:\\s*([^;]+);`))?.[1]?.trim();

async function main() {
  if (existsSync(OUT_DIR)) await rm(OUT_DIR, { recursive: true });
  await mkdir(OUT_DIR, { recursive: true });

  const rules = [];
  const files = [];

  for (const { query, family } of FAMILIES) {
    const url = `https://fonts.googleapis.com/css2?family=${query}&display=swap`;
    const res = await fetch(url, { headers: { 'user-agent': UA } });
    if (!res.ok) throw new Error(`${family}: CSS request failed with ${res.status}`);
    const css = await res.text();

    for (const { subset, body } of parseBlocks(css)) {
      if (!SUBSETS.has(subset)) continue;

      const src = field(body, 'src');
      const remote = src?.match(/url\((https:[^)]+\.woff2)\)/)?.[1];
      if (!remote) continue;

      const weight = field(body, 'font-weight')?.split(' ')[0] ?? '400';
      const style = field(body, 'font-style') ?? 'normal';
      const unicodeRange = field(body, 'unicode-range');
      const name = `${slug(family)}-${weight}-${subset}.woff2`;

      const fontRes = await fetch(remote, { headers: { 'user-agent': UA } });
      if (!fontRes.ok) throw new Error(`${name}: download failed with ${fontRes.status}`);
      const bytes = Buffer.from(await fontRes.arrayBuffer());
      await writeFile(`${OUT_DIR}/${name}`, bytes);
      files.push({ name, bytes: bytes.length });

      rules.push(
        [
          '@font-face {',
          `  font-family: '${family}';`,
          `  font-style: ${style};`,
          `  font-weight: ${weight};`,
          '  font-display: swap;',
          `  src: url('/fonts/${name}') format('woff2');`,
          ...(unicodeRange ? [`  unicode-range: ${unicodeRange};`] : []),
          '}',
        ].join('\n'),
      );

      console.log(`  ${family} ${weight} ${subset} — ${(bytes.length / 1024).toFixed(1)} KB`);
    }
  }

  const header = [
    '/*',
    ' * Self-hosted web fonts — GENERATED by scripts/fetch-fonts.mjs.',
    ' * Do not edit by hand; re-run the script when the weight list changes.',
    ' *',
    ' * Sora (headings), Manrope (body) and JetBrains Mono are all licensed under',
    ' * the SIL Open Font License 1.1, which permits self-hosting and redistribution.',
    ' */',
    '',
  ].join('\n');

  await writeFile(OUT_CSS, `${header}${rules.join('\n\n')}\n`, 'utf8');

  const total = files.reduce((sum, f) => sum + f.bytes, 0);
  console.log(
    `\nWrote ${files.length} woff2 file(s) (${(total / 1024).toFixed(1)} KB total) to ${OUT_DIR}`,
  );
  console.log(`Wrote ${rules.length} @font-face rule(s) to ${OUT_CSS}`);
}

main().catch((error) => {
  console.error(`Font fetch failed: ${error.message}`);
  process.exit(1);
});
