/**
 * Seed the D1 catalogue from the product content.
 *
 * Reads `src/content/products/*.md` and emits `scripts/seed-catalog.sql`
 * (`INSERT OR REPLACE` into `products` + `product_faqs`). Accurate data only:
 * products come straight from frontmatter. Plans are **not** seeded here — the
 * per-tier prices are not in a shape we can trust, so they belong to a real
 * pricing pass (or the admin panel, P7) rather than an invented mapping.
 *
 *   node scripts/seed-catalog.mjs            # write the SQL
 *   npm run db:seed:local                    # write + apply to local D1
 *   npm run db:seed:remote                   # write + apply to remote D1
 */

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import matter from 'gray-matter';

const DIR = 'src/content/products';
const OUT = 'scripts/seed-catalog.sql';

const PLATFORMS = new Set(['MT4', 'MT5', 'MT4/MT5', 'none']);

const esc = (value) =>
  value === null || value === undefined || value === '' ? 'NULL' : `'${String(value).replace(/'/g, "''")}'`;
const num = (value) => {
  const n = Number(value);
  return Number.isFinite(n) ? n : 0;
};

const productRows = [];
const faqRows = [];

for (const file of readdirSync(DIR)) {
  if (!file.endsWith('.md')) continue;
  const { data } = matter(readFileSync(`${DIR}/${file}`, 'utf8'));

  const slug = String(data.slug ?? file.replace(/\.md$/, ''));
  const platform = PLATFORMS.has(data.platform) ? data.platform : 'none';
  const type = platform === 'none' ? 'tool' : 'ea';
  // Free only when every price signal is zero — a paid simple product keeps its
  // number and is therefore not free.
  const isFree = num(data.price) === 0 && num(data.priceMin) === 0 && num(data.priceMax) === 0;
  const imageKey = data.featuredImage ? String(data.featuredImage) : null;
  const now = Date.now();

  productRows.push(
    `INSERT OR REPLACE INTO products (id, slug, type, title, summary, description, platform, currency, is_free, active, image_key, created_at, updated_at) VALUES (${[
      esc(slug),
      esc(slug),
      esc(type),
      esc(data.title),
      esc(data.description),
      esc(data.quickAnswer ?? data.description),
      esc(platform),
      esc(data.currency ?? 'USD'),
      isFree ? 1 : 0,
      1,
      esc(imageKey),
      now,
      now,
    ].join(', ')});`
  );

  const faqs = Array.isArray(data.faqs) ? data.faqs : [];
  faqs.forEach((faq, i) => {
    if (!faq?.question || !faq?.answer) return;
    faqRows.push(
      `INSERT OR REPLACE INTO product_faqs (id, product_id, question, answer, sort_order, created_at) VALUES (${[
        esc(`${slug}-faq-${i}`),
        esc(slug),
        esc(faq.question),
        esc(faq.answer),
        i,
        Date.now(),
      ].join(', ')});`
    );
  });
}

const sql = [
  '-- generated by scripts/seed-catalog.mjs — do not edit by hand',
  ...productRows,
  ...faqRows,
  '',
].join('\n');

writeFileSync(OUT, sql);
console.log(`seed-catalog: ${productRows.length} products, ${faqRows.length} faqs -> ${OUT}`);
