/**
 * Seed D1 database reviews table from `src/data/reviews.json`.
 *
 * Usage:
 *   node scripts/seed-reviews.mjs
 *   wrangler d1 execute bestmt4ea --local --file=./scripts/seed-reviews.sql
 *   wrangler d1 execute bestmt4ea --remote --file=./scripts/seed-reviews.sql
 */

import { readFileSync, writeFileSync } from 'node:fs';

const SRC = 'src/data/reviews.json';
const OUT = 'scripts/seed-reviews.sql';

/**
 * Read JSON whatever encoding the file happens to be in. PowerShell's `>` and
 * `Out-File` write UTF-16LE by default, which used to surface here as
 * `SyntaxError: Unexpected token '�'` from JSON.parse.
 */
function readJson(path) {
  const bytes = readFileSync(path);
  if (bytes[0] === 0xff && bytes[1] === 0xfe) {
    return JSON.parse(new TextDecoder('utf-16le').decode(bytes.subarray(2)));
  }
  if (bytes[0] === 0xfe && bytes[1] === 0xff) {
    return JSON.parse(new TextDecoder('utf-16be').decode(bytes.subarray(2)));
  }
  if (bytes[0] === 0xef && bytes[1] === 0xbb && bytes[2] === 0xbf) {
    return JSON.parse(new TextDecoder('utf-8').decode(bytes.subarray(3)));
  }
  return JSON.parse(new TextDecoder('utf-8').decode(bytes));
}

/**
 * Only wording the customer has confirmed as their own may be inserted.
 * `provenance: "customer-order"` means the entry came from an order record — the
 * order is real, the wording is not the customer's — so it is skipped here, the
 * same rule `/customer-feedback/` applies when rendering.
 */
const CONFIRMED_PROVENANCE = new Set(['customer-confirmed', 'customer-provided']);

const data = readJson(SRC);
const reviews = data.reviews ?? [];

const esc = (value) =>
  value === null || value === undefined ? 'NULL' : `'${String(value).replace(/'/g, "''")}'`;

function mapProduct(name) {
  if (!name) return null;
  const n = name.toLowerCase();
  if (n.includes('fxcore100')) return 'fxcore100-ea';
  if (n.includes('obsidian')) return 'obsidian-aether-eurusd-ea-ai-grid-scalper-for-mt5';
  if (n.includes('ava aigpt5') || n.includes('ava')) return 'ava-aigpt5-ea';
  if (n.includes('apex') || n.includes('bitcoin scalper')) return 'apex-quant-ea-ai-bitcoin-scalper-for-mt5';
  if (n.includes('vps')) return 'vps';
  if (n.includes('onix')) return 'onix-stratos-xauusd-ea-ai-smart-scalper-for-mt5';
  if (n.includes('nexora')) return 'nexora-manus-ea-ai-gold-scalper-for-mt5';
  if (n.includes('mythos')) return 'mythos-epic-ea-ai-gold-scalper-for-mt5';
  if (n.includes('zenith')) return 'zenith-matrix-ea-ai-gold-scalper-for-mt5';
  if (n.includes('elysium')) return 'elysium-vortex-eurcad-ea-ai-eurcad-scalper-for-mt5';
  if (n.includes('equinox') || n.includes('cosmos')) return 'equinox-cosmos-ea-ai-gbpjpy-scalper-for-mt5';
  if (n.includes('golden deer')) return 'golden-deer-holy-grail-indicator';
  return null;
}

const sqlLines = ['-- Auto-generated by scripts/seed-reviews.mjs', ''];

let matchedCount = 0;
let unconfirmed = 0;
let unmatched = 0;
for (const item of reviews) {
  if (!CONFIRMED_PROVENANCE.has(String(item.provenance ?? ''))) {
    unconfirmed += 1;
    continue;
  }
  const productId = mapProduct(item.product);
  if (!productId) {
    unmatched += 1;
    continue;
  }

  matchedCount++;
  const id = `rev_${item.id}`;
  const reviewerName = item.reviewer ?? 'Verified customer';
  const rating = Number(item.rating) || 5;
  const bodyText = item.title ? `${item.title} — ${item.body}` : item.body;

  let createdAtMs = Date.now();
  if (item.month) {
    const parsed = new Date(`${item.month} 1 UTC`);
    if (!isNaN(parsed.getTime())) {
      createdAtMs = parsed.getTime();
    }
  }

  sqlLines.push(
    `INSERT OR REPLACE INTO reviews (id, product_id, customer_id, reviewer_name, rating, body, hidden_at, created_at, updated_at) VALUES (` +
      `${esc(id)}, ` +
      `${esc(productId)}, ` +
      `NULL, ` +
      `${esc(reviewerName)}, ` +
      `${rating}, ` +
      `${esc(bodyText)}, ` +
      `NULL, ` +
      `${createdAtMs}, ` +
      `${createdAtMs}` +
      `);`
  );
}

// `wrangler d1 execute` refuses a file with no statements, so emit an explicit no-op.
if (matchedCount === 0) sqlLines.push('SELECT 1 AS no_reviews_to_seed;');

writeFileSync(OUT, sqlLines.join('\n') + '\n', 'utf8');
console.log(`Generated ${matchedCount} review insert statements -> ${OUT}`);
if (unconfirmed) {
  console.log(
    `Skipped ${unconfirmed}: wording not confirmed by the customer. "customer-order" provenance means the ` +
      'entry was derived from an order record, not written by the customer — set provenance to ' +
      '"customer-confirmed" once they have agreed the wording is theirs.'
  );
}
if (unmatched) console.log(`Skipped ${unmatched}: product not found in the catalogue.`);
