import { defineCollection, z } from 'astro:content';
import { glob } from 'astro/loaders';

/**
 * Content model for the BESTMT4EA rebuild.
 *
 * Mirrors the WordPress source so URLs, slugs and SEO metadata survive 1:1:
 *   - products -> /product/<slug>/   (WooCommerce `product`)
 *   - posts    -> /<slug>/           (WP `post`, root-level permalinks)
 *   - pages    -> /<slug>/           (WP `page`)
 *
 * Frontmatter is generated by scripts/wp-export.mjs. Editorial extras
 * (quickAnswer, keyTakeaways, faqs, download) are optional so a re-export never
 * wipes them, and are validated by scripts/check-content.mjs.
 */

/**
 * WordPress exports emoji slugs percent-encoded (e.g. `%f0%9f%8c%8a-neptune…`),
 * but the canonical URL is the decoded emoji. Astro 7 matches the decoded path,
 * so decode once here — every route param, link and canonical then agrees.
 */
const decodeSlug = (value: string) => {
  try {
    return decodeURIComponent(value);
  } catch {
    return value;
  }
};

const seo = z
  .object({
    title: z.string().optional(),
    description: z.string().optional(),
    canonical: z.string().optional(),
    robots: z.string().optional(),
    ogImage: z.string().optional(),
  })
  .default({});

const base = z.object({
  wpId: z.number().int().optional(),
  title: z.string(),
  slug: z.string().transform(decodeSlug),
  description: z.string().default(''),
  publishedAt: z.coerce.date(),
  updatedAt: z.coerce.date().optional(),
  author: z.string().optional(),
  featuredImage: z.string().optional(),
  seo,
  draft: z.boolean().default(false),
  sourceUrl: z.string().optional(),
});

/** A downloadable file, either hosted by us or linked to its origin. */
const download = z
  .object({
    /** own = we made it. opensource = third-party, must be credited. */
    origin: z.enum(['own', 'opensource']),
    license: z.string().min(1),
    licenseUrl: z.string().url().optional(),
    /** Required when origin is opensource. */
    author: z.string().optional(),
    sourceUrl: z.string().url().optional(),
    version: z.string().optional(),
    platform: z.enum(['MT4', 'MT5', 'MT4/MT5']).optional(),
    fileSize: z.string().optional(),
    /** Hosted on our storage. */
    fileKey: z.string().optional(),
    /** Or link straight to the origin. */
    externalUrl: z.string().url().optional(),
    updatedAt: z.coerce.date().optional(),
  })
  .refine((d) => d.origin !== 'opensource' || Boolean(d.author && d.sourceUrl), {
    message: 'Open-source downloads must credit the original author and link to the source.',
  })
  .refine((d) => Boolean(d.fileKey || d.externalUrl), {
    message: 'A download needs either a fileKey (hosted) or an externalUrl.',
  });

const faq = z.object({ question: z.string().min(5), answer: z.string().min(20) });
const source = z.object({ label: z.string(), url: z.string().url() });

const products = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/products' }),
  schema: base.extend({
    platform: z.enum(['MT4', 'MT5', 'MT4/MT5', 'none']).default('none'),
    productCategories: z.array(z.string()).default([]),
    brands: z.array(z.string()).default([]),
    tags: z.array(z.string()).default([]),
    price: z.string().optional(),
    regularPrice: z.string().optional(),
    salePrice: z.string().optional(),
    currency: z.string().default('USD'),
    priceMin: z.number().optional(),
    priceMax: z.number().optional(),
    sku: z.string().optional(),
    stockStatus: z.string().optional(),
    productType: z.enum(['simple', 'variable', 'grouped', 'external', 'unknown']).default('unknown'),
    variants: z
      .array(
        z.object({
          id: z.number().int().optional(),
          name: z.string().optional(),
          sku: z.string().optional(),
          price: z.string().optional(),
          regularPrice: z.string().optional(),
          salePrice: z.string().optional(),
        }),
      )
      .default([]),
    gallery: z.array(z.string()).default([]),
    systemPage: z.boolean().default(false),

    /** Editorial extras. */
    quickAnswer: z.string().optional(),
    keyTakeaways: z.array(z.string()).default([]),
    faqs: z.array(faq).default([]),
    sources: z.array(source).default([]),
    primaryKeyword: z.string().optional(),
    related: z.array(z.string()).default([]),
  }),
});

const posts = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/posts' }),
  schema: base.extend({
    categories: z.array(z.string()).default([]),
    categoryPaths: z.array(z.string()).default([]),
    tags: z.array(z.string()).default([]),
    /** Old WP category paths, for /category/... URL parity. */

    /** Editorial extras — see docs/CONTENT-STANDARD.md. */
    quickAnswer: z.string().optional(),
    keyTakeaways: z.array(z.string()).default([]),
    faqs: z.array(faq).default([]),
    sources: z.array(source).default([]),
    primaryKeyword: z.string().optional(),
    updatedNote: z.string().optional(),
    /** Turns a post into a free-download page. */
    download: download.optional(),
    /**
     * Ordered install steps. Rendered above the fold on download pages so
     * there is genuine content between the download button and the first ad,
     * and so the page can carry HowTo structured data.
     */
    installSteps: z.array(z.object({ name: z.string().min(3), text: z.string().min(10) })).default([]),
  }),
});

const pages = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/pages' }),
  schema: base.extend({
    systemPage: z.boolean().default(false),
    menuOrder: z.number().int().default(0),
    faqs: z.array(faq).default([]),
    showAds: z.boolean().default(true),
  }),
});

export const collections = { products, posts, pages };
